lib/lynx_web/router.ex
defmodule LynxWeb.Router do
  @moduledoc """
  Handles application routing between controllers and views
  """
  use LynxWeb, :router
  alias Lynx.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plug.Authentication
    # plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug Plug.EnsureAuthentication
  end

  ## Not currently using Auth0 because return value
  ## %{id: id, email: email, name: name} can't be validated by ecto

  #   scope "/auth", LynxWeb do
  #     pipe_through :browser

  #     get "/:provider", SessionController, :request
  #     get "/:provider/callback", SessionController, :callback
  #     post "/:provider/callback", SessionController, :callback
  #   end

  scope "/", LynxWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources("/users", UserController, only: [:new, :create, :show, :index])
    resources("/session", SessionController, only: [:create, :new, :delete])
  end

  scope "/", LynxWeb do
    pipe_through [:browser, :authenticated]
    resources("/users", UserController, only: [:delete, :edit, :update])
    resources("/session", SessionController, only: [:delete])
  end

  # Other scopes may use custom stacks.
  # scope "/api", LynxWeb do
  #   pipe_through :api
  # end

  ### Private functions ###
  #   defp put_user_token(conn, _) do
  #     if current_user = conn.assigns[:current_user] do
  #       token = Phoenix.Token.sign(conn, "user socket", current_user.id)
  #       assign(conn, :user_token, token)
  #     else
  #       conn
  #     end
  #   end
end

lib/lynx_web/views/layout_view.ex
defmodule LynxWeb.LayoutView do
  use LynxWeb, :view

  def title() do
    "Lynx"
  end
end

lib/lynx_web/templates/layout/_navbar.html.eex
  <div class="ui fixed inverted menu">
    <div class="ui container">
      <a href="/" class="header item">
        <img class="logo" src="/images/lynx.png">
        <span class="app-name"> Lynx </span>
      </a>
      <div class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="#">Link Item</a>
          <a class="item" href="#">Link Item</a>
          <div class="divider"></div>
          <div class="header">Header Item</div>
          <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
              <a class="item" href="#">Link Item</a>
              <a class="item" href="#">Link Item</a>
            </div>
          </div>
          <a class="item" href="#">Link Item</a>
        </div>
      </div>
        <div class="right menu">
        <%= if Lynx.Accounts.get_current_user(@conn) do %>
            <!-- User Profile -->
            <div class="item">
                <%= link raw(~s'<i class="user circle icon"></i>Profile'), to: Routes.user_path(@conn, :show, Guardian.Plug.current_resource(@conn).id), class: "ui compact button" %>
            </div>
            <!-- Log out -->
            <div class="item">
                <%= link raw(~s'<i class="sign out alternate icon"></i>Logout'), to: Routes.session_path(@conn, :new), method: :delete, class: "ui compact red button" %>
            </div>

        <% else %>
            <div class="item">
                <%= link raw(~s'<i class="sign in alternate icon"></i>Login'), to: Routes.session_path(@conn, :new), class: "ui compact primary button"%>
            </div>
            <div class="item">
                <%= link raw(~s'<i class="user icon"></i>Sign up'), to: Routes.user_path(@conn, :new), class: "ui compact teal button" %>
            </div>
            <!-----
                <div class="item">
                <%= link raw(~s'<i class="sign in alternate icon"></i>Auth0 Sign-in'), to: "/auth/auth0", class: "tiny ui compact purple button"%>
                </div>
            ---->
        <% end %>
        </div>
    </div>
  </div>

lib/lynx_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title() %></title>
    <%= if Lynx.Accounts.get_current_user(@conn) do %>
    <%= tag :meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user socket", Guardian.Plug.current_resource(@conn).id) %>
    <% else %>
    <% end %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>

    <%= render "_navbar.html", conn: @conn %>
      <br>
      <br>

    <div class="ui main container">
        <main role="main">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
        </main>
    </div>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>